### ISSUE TITLE
[TODO] Code Change

### ISSUE THREAD

**Issue by cyfung1031** [cvzi/genius-lyrics-userscript#79]
* [ ] to replace `innerHTML` to `textContent`
* [ ] to replace `innerHTML` to `elmBuild`
* [x] fix romaji detection according to the latest result format
* [x] filter out deleted lyrics by detecting "Deleted Artist"

```js
const elmBuild = (tag, ...contents) => {
  /** @type {HTMLElement} */
  const elm = typeof tag === 'string' ? document.createElement(tag) : tag;
  for (const content of contents) {
    if (!content || typeof content !== 'object' || (content instanceof Node)) {
      elm.append(content)
    } else if (content.length > 0) {
      elm.appendChild(elmBuild(...content))
    } else if (content.style) {
      Object.assign(elm.style, content.style);
    } else if (content.classList) {
      elm.classList.add(...content.classList)
    } else if (content.attr) {
      for (const [attr, val] of Object.entries(content.attr)) elm.setAttribute(attr, val);
    } else {
      Object.assign(elm, content)
    }
  }
  return elm;
}
```

```js
const elmBuildNS = (tag, ...contents) => {
  const ns = 'http://www.w3.org/2000/svg'
  /** @type {Element} */
  const elm = typeof tag === 'string' ? document.createElementNS(ns, tag) : tag;
  for (const content of contents) {
    if (!content || typeof content !== 'object' || (content instanceof Node)) {
      elm.append(content)
    } else if (content.length > 0) {
      elm.appendChild(elmBuildNS(...content))
    } else if (content.style) {
      Object.assign(elm.style, content.style);
    } else if (content.classList) {
      elm.classList.add(...content.classList)
    } else if (content.attr) {
      for (const [attr, val] of Object.entries(content.attr)) elm.setAttributeNS(ns, attr, val);
    } else {
      Object.assign(elm, content)
    }
  }
  return elm;
}
```

Coding Example
```js
elmBuild(container,
  ['h2',
    'This script only works in ',
    ['a', {
      'target': '_blank',
      'href': 'https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/'
    }, 'Tampermonkey'],
  ],
  'Greasemonkey is no longer supported because of this ',
  ['a', {
    'target': '_blank',
    'href': 'https://github.com/greasemonkey/greasemonkey/issues/2574'
  }, 'bug greasemonkey/issues/2574'],
  ' in Greasemonkey.',
)
```

## Preview
* https://raw.githubusercontent.com/cvzi/genius-lyrics-userscript/abeee7bc0cec240b79278efb4145a3cd26082874/GeniusLyrics.js
